### ISSUE TITLE
Have trouble running the pretrained policy

### ISSUE THREAD

**Issue by RyanJiao** [leap-hand/LEAP_Hand_Sim#1]
I finished setting up the envirment and run the code
_python3 train.py wandb_activate=false num_envs=1 headless=false test=true task=LeapHandRot checkpoint=runs/pretrained/nn/LeapHand.pth_
and then error ocurred :
FileNotFoundError: [Errno 2] No such file or directory: 'cache/leap_hand_in_palm_cube_grasp_50k_s095.npy'
How can I fix it?

**Comment by RyanJiao** [comment]
![image](https://github.com/leap-hand/LEAP_Hand_Sim/assets/56286149/976b88fc-8a9e-4ffe-b533-73a3ee7e7cbe)

**Comment by leap-hand** [comment]
Hi @RyanJiao 

I think you have an out of memory error, we used a RTX 3090 with 24GB vRAM.  I would suggest you try decreasing the number of parallel environments in the yaml file.

**Comment by anag004** [comment]
What GPU are you using to run the code? Seems like the vRAM might not be enough. You can try running on CPU by specifying `pipeline=cpu`.

```python3 deploy.py wandb_activate=false num_envs=1 headless=false test=true task=LeapHandRot checkpoint=runs/pretrained/nn/LeapHand.pth pipeline=cpu ```

Another thing could be to turn off VHACD here (just change `True` to `False`) **https://github.com/leap-hand/LEAP_Hand_Sim/blob/0e9f0a3de7f38281f71ba88e5dade4d6a6586dac/leapsim/tasks/leap_hand_rot.py#L981**.

**Comment by RyanJiao** [comment]
Hi! while excuting this: I encountered a new fault. Do you any clue to solve this? Thanks again for your help!
for cube_scale in 0.9 0.95 1.0 1.05 1.1  do 	bash scripts/gen_grasp.sh $cube_scale custom_grasp_cache num_envs=1024  done



焦睿轩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leap-hand/LEAP_Hand_Sim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 凌晨3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leap-hand/LEAP_Hand_Sim] Have trouble running the pretrained policy (Issue #1)





 
What GPU are you using to run the code? Seems like the vRAM might not be enough. You can try running on CPU by specifying pipeline=cpu.
 
python3 deploy.py wandb_activate=false num_envs=1 headless=false test=true task=LeapHandRot checkpoint=runs/pretrained/nn/LeapHand.pth pipeline=cpu 
 
Another thing could be to turn off VHACD here (just change True to False) https://github.com/leap-hand/LEAP_Hand_Sim/blob/0e9f0a3de7f38281f71ba88e5dade4d6a6586dac/leapsim/tasks/leap_hand_rot.py#L981

**Comment by RyanJiao** [comment]
Hi! I only have a RTX3060 with 6GB memory, I run the pretrained policy by reducing the minibatch_size to 1 with num_envs=1, I wander if I can sucessfully train any policy on my RTX3060, If it can't make it, I will change my graphcard.&nbsp; Many thanks!




焦睿轩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leap-hand/LEAP_Hand_Sim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 凌晨2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leap-hand/LEAP_Hand_Sim] Have trouble running the pretrained policy (Issue #1)





 
Hi @RyanJiao
 
I think you have an out of memory error, we used a RTX 3090 with 24GB vRAM.  I would suggest you try decreasing the number of parallel environments in the yaml file.

**Comment by anag004** [comment]
> Hi! while excuting this: I encountered a new fault. Do you any clue to solve this? Thanks again for your help! for cube_scale in 0.9 0.95 1.0 1.05 1.1 do bash scripts/gen_grasp.sh $cube_scale custom_grasp_cache num_envs=1024 done 焦睿轩 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "leap-hand/LEAP_Hand_Sim" ***@***.***&gt;; 发送时间:&nbsp;2023年9月19日(星期二) 凌晨3:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [leap-hand/LEAP_Hand_Sim] Have trouble running the pretrained policy (Issue #1) What GPU are you using to run the code? Seems like the vRAM might not be enough. You can try running on CPU by specifying pipeline=cpu. python3 deploy.py wandb_activate=false num_envs=1 headless=false test=true task=LeapHandRot checkpoint=runs/pretrained/nn/LeapHand.pth pipeline=cpu Another thing could be to turn off VHACD here (just change True to False) https://github.com/leap-hand/LEAP_Hand_Sim/blob/0e9f0a3de7f38281f71ba88e5dade4d6a6586dac/leapsim/tasks/leap_hand_rot.py#L981 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Hi, could you please comment directly on GitHub instead of through email? I think the image you sent was not included.

**Comment by RyanJiao** [comment]
OK！ This problem had been solved, Thank you!

**Comment by lixiaolong04** [comment]
> 好的！这个问题已经解决了，谢谢！

I am also trying to solve this problem. My launch file works well, but my deploy file does not. Can we talk about it together? Thank you
