### ISSUE TITLE
Re-training of the robotic LEAP Hand

### ISSUE THREAD

**Issue by AdrianPrados** [leap-hand/LEAP_Hand_Sim#11]
My name is Adrian Prados and I am a PhD student at the Universidad Carlos III de Madrid. We are replicating the LEAP Hand as we see that it has a great utility to be used. We are doing the training process following its exact steps and two problems have arisen. The first one is the amount of memory space on the graphics card. In our case we are training with a 10GB RTX 3060. By default there are 16000 environments and with this size there is not enough space. For this reason, in the cfg\config.yaml we have added the maximum number of environments that our graphics card supports (4096 envs). In this case we are not getting results as good as those presented on GitHub with the pre-trained models. We don't know if we have to modify any other parameter or if we have to modify the training hyperparameters.
The second question comes from the training generation of the grasping elements: can only cubes be generated?, can any other object be added?
Would it be possible to get some further documentation or information on how to train the hand and how to try to solve these problems? Thank you very much in advance for your answer.

**Comment by Lucky7Chess** [comment]
Hi Adrian,

Thank you for reaching out.  These questions are more about Isaac Gym and sim2real than LEAP Hand itself.

For the environments, yes we train with a 3090 with 24gb of memory so we can use 16000 environments.  We have found that you may have to slightly alter the hyperparameters to allow for the proper training.

For grasping, no you should be able to use different objects.  You would have to change the URDF/object stl to match that new object.

The documentation for how to solve these issues would be more in the Isaac Gym instructions and other papers that focus more on the RL problem than LEAP Hand.  LEAP Hand is more about the hardware itself and this repository is an example using the hand.
