### ISSUE TITLE
The object poses are not reset properly

### ISSUE THREAD

**Issue by Director-of-G** [leap-hand/LEAP_Hand_Sim#13]
I was training RL using the released code, but facing several problems.

1. The function `reset_idx` in `leapsim/tasks/leap_hand_rot.py` tries to reset the object pose and hand joint positions according to the generated `.npy` files in `cache` folder. Not sure if I am understanding this right.

2. I added the following lines to `leapsim/tasks/leap_hand_rot.py`, after line 511. I use the codes of [this version](https://github.com/leap-hand/LEAP_Hand_Sim/blob/ebc49e00af34b2634b1e6c746d962072fbb2f281/leapsim/tasks/leap_hand_rot.py#L511).
```
# [debug]
delta_rpy = torch_rand_float(0, 4, (len(s_ids), 3), device=self.device).int() * (torch.pi / 2.0)
delta_rot = quat_from_euler_xyz(delta_rpy[:, 0], delta_rpy[:, 1], delta_rpy[:, 2])
new_rot = quat_mul(sampled_pose[:, 16+3:16+7], delta_rot)
self.root_state_tensor[self.object_indices[s_ids], 3:7] = new_rot
```
These lines should override the objects' orientation by multiplies of pi/2 in roll, pitch and yaw. However, the reset object poses are always the same, as shown in the figure below.
![figure_debug](https://github.com/leap-hand/LEAP_Hand_Sim/assets/73640657/bf34ac2b-63ff-45c9-a020-f74dbe1e66b2)
Actually, this is exactly the default position when loading the object using `create_actor`. In other words, the object poses are not reset properly. This is unusual as official IsaacGymEnvs environments such as [FrankaCubeStack](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/isaacgymenvs/tasks/franka_cube_stack.py) could reset objects at different poses.

I use IsaacGymPreview4 and rl-games==1.5.2. I am not sure if this problem only appears in my settings.

**Comment by Director-of-G** [comment]
Besides, I was not able to train with other GPUs such as 'cuda:1'. I modifed the following items in config.yaml

```
## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:1'    # 'cuda:0' or 'cuda:1'
# device to run RL
rl_device: 'cuda:1'     # 'cuda:0' or 'cuda:1'
graphics_device_id: 1
```

Actually these modifications are enough to train ofiicial IsaacGymEnvs examples with 'cuda:1'.
I got the following error output:

```
[Error] [carb.gym.plugin] Gym cuda error: an illegal memory access was encounter
ed: ../../../source/plugins/carb/gym/impl/Gym/GymPhysXCuda.cu: 1107             
Error executing job with overrides: ['task=LeapHandRotGoal', 'task.env.object.ty
pe=cube_small', 'max_iterations=10000', 'task.env.grasp_cache_name=cube_small_ca
che2', 'wandb_activate=false', 'headless=true']

// I omit the traceback here

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so t
he stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Segmentation fault (core dumped)
```

Can anyone reproduce this error?

**Comment by Director-of-G** [comment]
I temporarily solve the first issue by renaming the cube with anything other than 'object' in [the code](https://github.com/leap-hand/LEAP_Hand_Sim/blob/ebc49e00af34b2634b1e6c746d962072fbb2f281/leapsim/tasks/leap_hand_rot.py#L410). But what is the reason?

**Comment by Lucky7Chess** [comment]
To be honest, I am unsure of the issue with cuda:1.  It is probably an Isaac Gym bug, and not something that I have control of.  The object should be reset to any orientation, but there may be a bug with Isaac there too.
