### ISSUE TITLE
we are trying to train the hand we 3 fingers and not 4

### ISSUE THREAD

**Issue by Shafik2b** [leap-hand/LEAP_Hand_Sim#14]
Hello
We are trying to remove one finger from the hand and train it to rotate the cube with 3 fingers.
Can you give us a direction on how it could be done?
What we done so far:
in file LeapHandRotYaml we changed :
       1. #numActions: 16 - > 12(because no we have 3 fingers)
        2.numOfObservation we don't know how to calculate it
also in assets/leap_hand/robot.urdf , we did changes , we removed a specific finger and all the related parts
mean while we are trying to train it to rotate the cube but its not happening

can you please help us and give us direction to which files we need to change also in order to do the training

Thank You.

**Comment by Lucky7Chess** [comment]
This is more of an Isaac gym question but this is right.  You need to change the URDF, change the number of observations and actions.  Then you should be able to retrain.  You may have to do some small edits to the reward or where the cube initiates on the hand to make it work....not sure.
