### ISSUE TITLE
we are trting to addjust the leapHandRot to 3 fingers

### ISSUE THREAD

**Issue by Shafik2b** [leap-hand/LEAP_Hand_Sim#15]
hi , we are trying to train the leapHandRot to rotate the cube with only 3 fingers
we modified a few changes in a few files that are uploaded down
we are failing for malloc problem when trying to train it to 1024 env
can you please tell us where this problem could be? or at least give us direction on how can we debug such fail?
this is the relevant fail:
Finished convex decomposition for mesh '/home/hand/IsaacGym_Preview_4_Package/isaacgym/python/LEAP_Hand_Sim/leapsim/tasks/../../assets/leap_hand/dip.stl': 9 hulls
Finished convex decomposition for mesh '/home/hand/IsaacGym_Preview_4_Package/isaacgym/python/LEAP_Hand_Sim/leapsim/tasks/../../assets/leap_hand/thumb_dip.stl': 12 hulls
Finished convex decomposition for mesh '/home/hand/IsaacGym_Preview_4_Package/isaacgym/python/LEAP_Hand_Sim/leapsim/tasks/../../assets/leap_hand/thumb_pip.stl': 43 hulls
Finished convex decomposition for mesh '/home/hand/IsaacGym_Preview_4_Package/isaacgym/python/LEAP_Hand_Sim/leapsim/tasks/../../assets/leap_hand/palm_lower.stl': 34 hulls
malloc(): invalid next size (unsorted)
Aborted (core dumped)

these are the relevant files that we did the change on:
https://github.com/Shafik2b/Leap_Hand_Rotate_3_Fingers/tree/main
we will appreciate any kind of help!!!
than you

**Comment by Lucky7Chess** [comment]
I have run into this very annoying bug on Isaac Gym too.  One thing you can try is to change the stl resolution, downward in this case.  You can use online tools for this, as long as they keep the home pose on the stl the same you should be okay.   For some reason the Isaac importer will crash on some stl resolutions but there is no consistency.  If that isn't it, then you may have a bug in your URDF.  You can also try to import the URDF into mujoco to make sure it imports on there.  It also gives you better error messages.

**Comment by Shafik2b** [comment]
hello , than you for the help , we tried to reduce the resolution yet we faced a lot of noise in the env , all the element were in places else that they should be
could you please tell us which tool did you used in order to reduce the resulotion?
so maybe that is the problem

we will appreciate any kind of help
Thank you

**Comment by Lucky7Chess** [comment]
I am not sure what noise means.  You need to down sample the resolution without changing the home pose of the stl.  Otherwise you will have to rewrite the URDF to account for the home pose change.  There are many off the shelf tools that will let you do this.
