### ISSUE TITLE
for how long do we need to train the model in order to start rotating the cube

### ISSUE THREAD

**Issue by Shafik2b** [leap-hand/LEAP_Hand_Sim#16]
hello,we are trying to train the hand with 3 fingers to rotate the cube , we can see that the reward is changing yet we not getting the result we want
for how long did you train the hand?
and another question
as I can see that the training is only for 5000 epoch, do we need to train it for more than that in order to start rotating the cube? and is there any parameters that need to be changed while training the hand?

i will be happy if you could help or at least give direction
Thank you

**Comment by Lucky7Chess** [comment]
If you are using 3 fingers the task may be considerably harder.  You may have to change the cube dimensions, the reward function etc to get the hand to spin it.

**Comment by Shafik2b** [comment]
okay i understand , and another question 
for how long did you trained the model?
