### ISSUE TITLE
for how long did you trained the model?

### ISSUE THREAD

**Issue by Shafik2b** [leap-hand/LEAP_Hand_Sim#17]
hi , for how long did you train the model?
how many epochs?
because i tried to train you model from scratch for 5000 epochs yet i didnt get to the result that you got

can you help me please?

Thanks

**Comment by Lucky7Chess** [comment]
Honestly it's going to depend on your number of envs and settings so I can't really give you a clear answer on how long you have to train for.  If the performance is improving or to a point where you are happy with it or plateauing, then that's probably long enough.

**Comment by Shafik2b** [comment]
yes , we running the samed settings with num_env == 1024
and we want to know approximetly about how many epochs to train it
because we tried to train it for 5000 epochs and we saw that the rewards are improving yet it still didnt rotate the cube
