### ISSUE TITLE
Problems following the Installation section

### ISSUE THREAD

**Issue by wredsen** [leap-hand/LEAP_Hand_Sim#2]
First of all: Thanks a lot for this awesome project!

I faced minor problems after directly following the instructions provided in the Installations section and trying to run the pretrained policy but could fix them:

1.  I was required to additionally install git python: `pip install gitpython`
2. I had to downgrade my default numpy version due to the usage of `numpy.float`: `pip install "numpy<1.24"`

Besides that:
Do you know any way to use isaacgym on Ubuntu 22.04 instead of Ubuntu 20?
The omniisaacgymenvs are compatible with Ubuntu 22, but I know to little if this project could be using these libraries instead.

**Comment by anag004** [comment]
> I faced minor problems after directly following the instructions provided in the Installations section and trying to run the pretrained policy but could fix them:

Thanks for pointing these out! We have updated the README with these instructions. 

> Do you know any way to use isaacgym on Ubuntu 22.04 instead of Ubuntu 20?

The usual installation method should work? Are you using preview 4? Can you post the error that you run into?

**Comment by wredsen** [comment]
Finally I managed to isaacgym on Ubuntu 22.04!

After pulling the updated state of this repo I just had to install a g++ compiler:
`sudo apt install build-essential
`

Now I can run the pretrained policy :)

**Comment by wredsen** [comment]
One more thing would be nice to mention: When using wandb (even for generating the cache), you have to set your wandb username in the `config.yaml` file :)

I did also run into the problem covered in this issue here: https://github.com/leap-hand/LEAP_Hand_Sim/issues/1#issuecomment-1726787214

After changing the line accordingly it works just fine.
