### ISSUE TITLE
Difference between trained .pth files?

### ISSUE THREAD

**Issue by Dharmik-P45** [leap-hand/LEAP_Hand_Sim#20]
I trained my own policy using the given instructions, and the training step resulted in .pth files in the last checkpoint that was created. The instructions say to use the "leaphand.pth" file in the command to visualize the policy, but running that shows a hand that initially seems correct, but the fingers shortly push the cube away. Running a different .pth file "last_LeapHand_ep_1000_rew_-324.62164" gives a better model, but still isn't able to rotate the cube. 

Does training also occur during the visualization or does it simply visualize a model that's already been 100% trained?

I had to lower the num envs due to memory limitations, from 16000 (default) to 1000. Could this result in a poorly trained model even if it trained to completion?

Another question: as per the instructions the training had occurred using different cube sizes. How can we visualize a specific cube size from the ones that were trained on?

**Comment by Lucky7Chess** [comment]
I do not know why this is not working for you in simulation.  The trained policy we provide should work out of the box.  Changing the number of envs will change the training dynamics though.

To show a certain cube, fix the size during test time in python.  Isaac gym supports this.

**Comment by Dharmik-P45** [comment]
Just a quick question about training. Is the range of possible objects for successful rotation slim? None of the irregular objects I've trained on rotate for more than like 20-30 seconds before falling off, and this is with the default number of environments with ample processing power and ram etc. Pic of the object attached:

I started from a 7.5 cm cube and just made it wavy, height is 7.5 cm exactly. **Would you expect this object to train properly** and rotate it just like a regular cube?


![wavy_cube](https://github.com/leap-hand/LEAP_Hand_Sim/assets/113470137/e5bb2940-49db-445e-99b0-d9d2d87ead3d)
