### ISSUE TITLE
Can you please release the onshape project of the LEAP hand?

### ISSUE THREAD

**Issue by Zi-ang-Cao** [leap-hand/LEAP_Hand_Sim#21]
Hi Authors,

Thank you for introducing this cost-efficient yet powerful dexterous hand to the robotics community. I am wondering if you could release the Onshape project of the LEAP hand. This would allow us to more easily export various model descriptions in MJCF/MJB. Additionally, it would make modifications to the palm and other parts more feasible. I believe releasing the assembled LEAP hand project on Onshape would enhance its significance and benefit other researchers in the field of dexterous hands as well.

Thank you!

Best regards,
Zi-ang Cao

**Comment by Lucky7Chess** [comment]
Mujoco viewer can convert between urdf and mjcf and can also import urdf directly.  I did not CAD in onshape so I cannot release files that way.
