### ISSUE TITLE
troublesome leap_hand_left.urdf

### ISSUE THREAD

**Issue by zhoubohan0** [leap-hand/LEAP_Hand_Sim#22]
Hi! About the left side of leap hand urdf, did you notice the collision of the mesh seems not that correct? This means, the thumb of leap hand left can not rotate freely and can easily get stuck with palm link. Is there any new version of leap hand urdf left?

**Comment by Lucky7Chess** [comment]
No,they should be the same.  You may not be importing the right collision masks into your simulation.
