### ISSUE TITLE
headless rendering

### ISSUE THREAD

**Issue by tarunc20** [leap-hand/LEAP_Hand_Sim#23]
Hi,

I'm trying to do headless rendering of the LeapHandRot environment, i.e., I want to be able to use ```env.render(mode="rgb_array")``` but I seem to be running into a few issues here. First, the LeapHandRot environment seems to inherit from the ```Env``` class, which doesn't support headless rendering within its render function, so I took a look at the ```VecTaskEnv``` class, which does appear to. However, when I try implementing the same logic, i.e., moving the virtual display code from ```VecTaskEnv``` to ```LeapHandRot```, I run into an issue where the viewer is needed, since otherwise the virtual display returns None as the image when ```virtual_display.grab()``` is called. I have a feeling that I'm potentially overcomplicating the issue, so if you have any suggestions, that would be greatly appreciated - thanks!

**Comment by Lucky7Chess** [comment]
This is an isaac gym issue, I encourage you to reach out to Nvidia forums about this.  This is not specific to LEAP Hand.
