### ISSUE TITLE
Does the author have any plans to build the train environment in Isaac Sim so that we can train the Hand in Issac Sim and deploy it with ROS2 on ubuntu 22.04

### ISSUE THREAD

**Issue by likecanyon** [leap-hand/LEAP_Hand_Sim#24]
Isaac Gym, NVIDIA's GPU-accelerated physics simulation environment for reinforcement learning, was originally designed for Ubuntu 18.04 and 20.04. While it is possible to install and run Isaac Gym on Ubuntu 22.04, users have reported encountering various issues during installation and execution. For instance, some have experienced display errors when running examples on Ubuntu 22.04, which were resolved by updating the NVIDIA driver to the latest version.
Given these challenges, NVIDIA recommends using Isaac Sim, a more comprehensive robotics simulation platform built on NVIDIA Omniverse, which offers full support for Ubuntu 22.04. Isaac Sim encompasses the functionalities of Isaac Gym and provides enhanced features, including robust support for ROS 2 integration.

**Comment by Lucky7Chess** [comment]
This is not an issue but a comment.  If you would like to run on Isaac Sim you can setup the URDF in that platform and run it.  I also have one but it's not external/finished right now.

**Comment by likecanyon** [comment]
> This is not an issue but a comment. If you would like to run on Isaac Sim you can setup the URDF in that platform and run it. I also have one but it's not external/finished right now.

Thank you for your rely. I kindly ask that would you like to publish the Isaac Sim version when you finish it?

**Comment by Lucky7Chess** [comment]
Yes of course when things are finished I will definitely release it....but no promises on timeline.

**Comment by likecanyon** [comment]
OK, I get it. Thank you for your prompt reply. Best of luck with your ongoing research:D
