### ISSUE TITLE
Could you please help me change the size of the cube?

### ISSUE THREAD

**Issue by likecanyon** [leap-hand/LEAP_Hand_Sim#25]
I changed the size of the cube in /assets/cube.urdf by "<box size="0.05 0.05 0.05"/>" and removed cached assets to force Isaac Gym to reload the URDF file by "rm -rf ~/.cache/isaacgym rm  -rf ~/.isaacgym", and then I restarted gym, but the size of the cube do not change. I found "object_asset = self.gym.load_asset(self.sim, asset_root, object_asset_file, object_asset_options)" in /tasks/leap_hand_rot.py, so I think the file should be reloaded and the size of the cube should change. But nothing different. I also tried to train a new policy under the modified size of the urdf file, the cube remained the same size. Could you please tell me how to change the size of the cube?

**Comment by Lucky7Chess** [comment]
This is an isaac gym question, not LEAP Hand specific.  Change the object scaling in gym or the URDF and it'll work.  Or load your own new object asset.

**Comment by likecanyon** [comment]
OK. Thank you for your prompt reply. Best of luck with your ongoing research:D
