### ISSUE TITLE
the question about the numActions

### ISSUE THREAD

**Issue by Young-Ace** [leap-hand/LEAP_Hand_Sim#27]
In the LeapHandRot.yaml configuration file, the value of 'numActions' is 16. How is this 16 calculated? If my hand has 5 fingers, how many do I need to set here?

**Comment by Lucky7Chess** [comment]
It's 4 per finger, MCP side, MCP forward, PIP, DIP.  I encourage you to check our website for further details.

**Comment by Young-Ace** [comment]
I see ,this parameter is exactly the number of motors/ the number of joints.thank you~
