### ISSUE TITLE
Feature request: headless + livestream

### ISSUE THREAD

**Issue by wredsen** [leap-hand/LEAP_Hand_Sim#5]
I am running this simulation on a remote machine.
For testing a trained policy the readme already suggests running:
```
python3 train.py wandb_activate=false num_envs=1 headless=false test=true task=LeapHandRot checkpoint=runs/<checkpoint_name>/nn/LeapHand.pth
```

It would be nice to also have a parameter  `enable_livestream`  (see https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs), so I can use the streaming client on my local machine.

**Comment by anag004** [comment]
The repo you linked to uses IsaacSim which is different from the simulator we use (IsaacGym). IsaacGym doesn't have native livestream support and implementing it would be non-trivial. An alternative for visualizing on headless machines is to use VNC (https://www.realvnc.com/en/)
