### ISSUE TITLE
LEAP Hand MuJoCo Support

### ISSUE THREAD

**Issue by cemoke** [leap-hand/LEAP_Hand_Sim#8]
Hi,

Is there any plan for using LEAP hand in MuJoCo?

I think it can be a quite nice addition to MuJoCo menagerie:
https://github.com/google-deepmind/mujoco_menagerie/blob/main/CONTRIBUTING.md

Best,

Cem

**Comment by Lucky7Chess** [comment]
Hi Cem,

Since we have fully released the URDF of the LEAP hand, you can import it and use it with MuJoCo easily.  Many labs have already done this.

While yes, there are many repos we can add our hand to, we will have to rely on the community to help us support everything out there. :)
